import { useEffect, useRef } from "react";
import { Globe, Brain, Paintbrush, FileCode } from "lucide-react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);

const features = [
  {
    icon: Globe,
    title: "Egypt Market Focus",
    desc: "Data sourced and analyzed specifically for Egyptian consumers. We understand local preferences, pricing sensitivity, and buying behaviors.",
  },
  {
    icon: Brain,
    title: "AI-Powered Analysis",
    desc: "Demand scoring, competitor tracking, SWOT analysis, and market sizing — all generated by AI trained on Egyptian e-commerce patterns.",
  },
  {
    icon: Paintbrush,
    title: "Ad Creative Generator",
    desc: "Generate Egyptian-market visuals, video scripts, headlines, and body copy optimized for Facebook, Instagram, and TikTok ads.",
  },
  {
    icon: FileCode,
    title: "Landing Page Builder",
    desc: "Pre-sell pages with complete structure, testimonials, FAQ, and the 5x pricing model built right in. Export and deploy in minutes.",
  },
];

export default function WhyGenie() {
  const sectionRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const ctx = gsap.context(() => {
      const cards = sectionRef.current?.querySelectorAll(".feature-card");
      if (cards) {
        gsap.fromTo(
          cards,
          { y: 60, opacity: 0 },
          {
            y: 0,
            opacity: 1,
            stagger: 0.15,
            duration: 1.0,
            ease: "power3.out",
            scrollTrigger: {
              trigger: sectionRef.current,
              start: "top 85%",
            },
          }
        );
      }
    }, sectionRef);
    return () => ctx.revert();
  }, []);

  return (
    <div className="relative" style={{ zIndex: 1, marginTop: "40vh" }}>
      <div
        ref={sectionRef}
        className="content-band max-w-[1280px] mx-auto"
        style={{ padding: "80px 6vw" }}
      >
        <div className="text-center mb-12">
          <h2 className="text-[#EAEAEF] text-[36px] sm:text-[48px] font-normal leading-[1.1] tracking-[-0.02em] mb-4">
            Why <span className="text-gradient">Genie</span>
          </h2>
          <p className="text-[#9494A8] text-[16px] sm:text-[18px] max-w-[500px] mx-auto">
            Everything you need to research, launch, and scale products in Egypt
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
          {features.map((f) => (
            <div
              key={f.title}
              className="feature-card card-glow p-8 flex flex-col items-start gap-4"
            >
              <div className="w-12 h-12 rounded-full bg-[rgba(157,140,255,0.1)] flex items-center justify-center">
                <f.icon className="w-5 h-5 text-[#9D8CFF]" />
              </div>
              <h3 className="text-[#EAEAEF] text-[20px] font-medium">{f.title}</h3>
              <p className="text-[#9494A8] text-[16px] font-normal leading-[1.6]">
                {f.desc}
              </p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
